#pragma once
// XXXih: This file is normally generated by a configure script or something, I
// guess. Just redirect to the hand-rolled file located in stubs/.
#include "../../../stubs/config-include/QtGui/qtgui-config.h"
