#!/bin/sh
ROOT="$(cd "$(dirname "$0")"/..; pwd -P)"
cd "$ROOT"

source ../sync-cfg.sh

err=$?
if [[ $? -ne 0 ]]; then
    echo "sync-cfg.sh not found";
    exit 1;
fi

unison "$ROOT"/src/msvcrt-support "$MSVCRT_SUPPORT_ROOT"

